//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 02:20:14 AM CEST 
//


package cz.mfcr.fs.eet.schema.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.mfcr.fs.eet.schema.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Trzba_QNAME = new QName("http://fs.mfcr.cz/eet/schema/v2", "Trzba");
    private final static QName _Odpoved_QNAME = new QName("http://fs.mfcr.cz/eet/schema/v2", "Odpoved");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.mfcr.fs.eet.schema.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrzbaType }
     * 
     */
    public TrzbaType createTrzbaType() {
        return new TrzbaType();
    }

    /**
     * Create an instance of {@link OdpovedType }
     * 
     */
    public OdpovedType createOdpovedType() {
        return new OdpovedType();
    }

    /**
     * Create an instance of {@link OdpovedPotvrzeniType }
     * 
     */
    public OdpovedPotvrzeniType createOdpovedPotvrzeniType() {
        return new OdpovedPotvrzeniType();
    }

    /**
     * Create an instance of {@link BkpElementType }
     * 
     */
    public BkpElementType createBkpElementType() {
        return new BkpElementType();
    }

    /**
     * Create an instance of {@link TrzbaKontrolniKodyType }
     * 
     */
    public TrzbaKontrolniKodyType createTrzbaKontrolniKodyType() {
        return new TrzbaKontrolniKodyType();
    }

    /**
     * Create an instance of {@link TrzbaDataType }
     * 
     */
    public TrzbaDataType createTrzbaDataType() {
        return new TrzbaDataType();
    }

    /**
     * Create an instance of {@link OdpovedChybaType }
     * 
     */
    public OdpovedChybaType createOdpovedChybaType() {
        return new OdpovedChybaType();
    }

    /**
     * Create an instance of {@link TrzbaHlavickaType }
     * 
     */
    public TrzbaHlavickaType createTrzbaHlavickaType() {
        return new TrzbaHlavickaType();
    }

    /**
     * Create an instance of {@link OdpovedHlavickaType }
     * 
     */
    public OdpovedHlavickaType createOdpovedHlavickaType() {
        return new OdpovedHlavickaType();
    }

    /**
     * Create an instance of {@link PkpElementType }
     * 
     */
    public PkpElementType createPkpElementType() {
        return new PkpElementType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrzbaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fs.mfcr.cz/eet/schema/v2", name = "Trzba")
    public JAXBElement<TrzbaType> createTrzba(TrzbaType value) {
        return new JAXBElement<TrzbaType>(_Trzba_QNAME, TrzbaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OdpovedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fs.mfcr.cz/eet/schema/v2", name = "Odpoved")
    public JAXBElement<OdpovedType> createOdpoved(OdpovedType value) {
        return new JAXBElement<OdpovedType>(_Odpoved_QNAME, OdpovedType.class, null, value);
    }

}
