//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 02:20:14 AM CEST 
//


package cz.mfcr.fs.eet.schema.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OdpovedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OdpovedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Hlavicka" type="{http://fs.mfcr.cz/eet/schema/v2}OdpovedHlavickaType"/>
 *         &lt;choice>
 *           &lt;element name="Potvrzeni" type="{http://fs.mfcr.cz/eet/schema/v2}OdpovedPotvrzeniType"/>
 *           &lt;element name="Chyba" type="{http://fs.mfcr.cz/eet/schema/v2}OdpovedChybaType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OdpovedType", propOrder = {
    "hlavicka",
    "potvrzeni",
    "chyba"
})
public class OdpovedType {

    @XmlElement(name = "Hlavicka", required = true)
    protected OdpovedHlavickaType hlavicka;
    @XmlElement(name = "Potvrzeni")
    protected OdpovedPotvrzeniType potvrzeni;
    @XmlElement(name = "Chyba")
    protected OdpovedChybaType chyba;

    /**
     * Gets the value of the hlavicka property.
     * 
     * @return
     *     possible object is
     *     {@link OdpovedHlavickaType }
     *     
     */
    public OdpovedHlavickaType getHlavicka() {
        return hlavicka;
    }

    /**
     * Sets the value of the hlavicka property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdpovedHlavickaType }
     *     
     */
    public void setHlavicka(OdpovedHlavickaType value) {
        this.hlavicka = value;
    }

    /**
     * Gets the value of the potvrzeni property.
     * 
     * @return
     *     possible object is
     *     {@link OdpovedPotvrzeniType }
     *     
     */
    public OdpovedPotvrzeniType getPotvrzeni() {
        return potvrzeni;
    }

    /**
     * Sets the value of the potvrzeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdpovedPotvrzeniType }
     *     
     */
    public void setPotvrzeni(OdpovedPotvrzeniType value) {
        this.potvrzeni = value;
    }

    /**
     * Gets the value of the chyba property.
     * 
     * @return
     *     possible object is
     *     {@link OdpovedChybaType }
     *     
     */
    public OdpovedChybaType getChyba() {
        return chyba;
    }

    /**
     * Sets the value of the chyba property.
     * 
     * @param value
     *     allowed object is
     *     {@link OdpovedChybaType }
     *     
     */
    public void setChyba(OdpovedChybaType value) {
        this.chyba = value;
    }

}
