//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 02:20:14 AM CEST 
//


package cz.mfcr.fs.eet.schema.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OdpovedHlavickaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OdpovedHlavickaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="uuid_zpravy" type="{http://fs.mfcr.cz/eet/schema/v2}UUIDType" />
 *       &lt;attribute name="bkp" type="{http://fs.mfcr.cz/eet/schema/v2}BkpType" />
 *       &lt;attribute name="dat_prij" type="{http://fs.mfcr.cz/eet/schema/v2}dateTime" />
 *       &lt;attribute name="dat_odmit" type="{http://fs.mfcr.cz/eet/schema/v2}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OdpovedHlavickaType")
public class OdpovedHlavickaType {

    @XmlAttribute(name = "uuid_zpravy")
    protected String uuidZpravy;
    @XmlAttribute(name = "bkp")
    protected String bkp;
    @XmlAttribute(name = "dat_prij")
    protected XMLGregorianCalendar datPrij;
    @XmlAttribute(name = "dat_odmit")
    protected XMLGregorianCalendar datOdmit;

    /**
     * Gets the value of the uuidZpravy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuidZpravy() {
        return uuidZpravy;
    }

    /**
     * Sets the value of the uuidZpravy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuidZpravy(String value) {
        this.uuidZpravy = value;
    }

    /**
     * Gets the value of the bkp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBkp() {
        return bkp;
    }

    /**
     * Sets the value of the bkp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBkp(String value) {
        this.bkp = value;
    }

    /**
     * Gets the value of the datPrij property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatPrij() {
        return datPrij;
    }

    /**
     * Sets the value of the datPrij property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatPrij(XMLGregorianCalendar value) {
        this.datPrij = value;
    }

    /**
     * Gets the value of the datOdmit property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatOdmit() {
        return datOdmit;
    }

    /**
     * Sets the value of the datOdmit property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatOdmit(XMLGregorianCalendar value) {
        this.datOdmit = value;
    }

}
