//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 02:20:14 AM CEST 
//


package cz.mfcr.fs.eet.schema.v2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TrzbaDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrzbaDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dic_popl" use="required" type="{http://fs.mfcr.cz/eet/schema/v2}CZDICType" />
 *       &lt;attribute name="dic_poverujiciho" type="{http://fs.mfcr.cz/eet/schema/v2}CZDICType" />
 *       &lt;attribute name="id_provoz" use="required" type="{http://fs.mfcr.cz/eet/schema/v2}IdProvozType" />
 *       &lt;attribute name="id_pokl" use="required" type="{http://fs.mfcr.cz/eet/schema/v2}string" />
 *       &lt;attribute name="porad_cis" use="required" type="{http://fs.mfcr.cz/eet/schema/v2}string" />
 *       &lt;attribute name="dat_trzby" use="required" type="{http://fs.mfcr.cz/eet/schema/v2}dateTime" />
 *       &lt;attribute name="celk_trzba" use="required" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="zakl_nepodl_dph" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="zakl_dan1" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="dan1" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="zakl_dan2" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="dan2" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="zakl_dan3" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="dan3" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="cest_sluz" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="pouzit_zboz1" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="pouzit_zboz2" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="pouzit_zboz3" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="urceno_cerp_zuct" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="cerp_zuct" type="{http://fs.mfcr.cz/eet/schema/v2}CastkaType" />
 *       &lt;attribute name="rezim" use="required" type="{http://fs.mfcr.cz/eet/schema/v2}RezimType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrzbaDataType")
public class TrzbaDataType {

    @XmlAttribute(name = "dic_popl", required = true)
    protected String dicPopl;
    @XmlAttribute(name = "dic_poverujiciho")
    protected String dicPoverujiciho;
    @XmlAttribute(name = "id_provoz", required = true)
    protected int idProvoz;
    @XmlAttribute(name = "id_pokl", required = true)
    protected String idPokl;
    @XmlAttribute(name = "porad_cis", required = true)
    protected String poradCis;
    @XmlAttribute(name = "dat_trzby", required = true)
    protected XMLGregorianCalendar datTrzby;
    @XmlAttribute(name = "celk_trzba", required = true)
    protected BigDecimal celkTrzba;
    @XmlAttribute(name = "zakl_nepodl_dph")
    protected BigDecimal zaklNepodlDph;
    @XmlAttribute(name = "zakl_dan1")
    protected BigDecimal zaklDan1;
    @XmlAttribute(name = "dan1")
    protected BigDecimal dan1;
    @XmlAttribute(name = "zakl_dan2")
    protected BigDecimal zaklDan2;
    @XmlAttribute(name = "dan2")
    protected BigDecimal dan2;
    @XmlAttribute(name = "zakl_dan3")
    protected BigDecimal zaklDan3;
    @XmlAttribute(name = "dan3")
    protected BigDecimal dan3;
    @XmlAttribute(name = "cest_sluz")
    protected BigDecimal cestSluz;
    @XmlAttribute(name = "pouzit_zboz1")
    protected BigDecimal pouzitZboz1;
    @XmlAttribute(name = "pouzit_zboz2")
    protected BigDecimal pouzitZboz2;
    @XmlAttribute(name = "pouzit_zboz3")
    protected BigDecimal pouzitZboz3;
    @XmlAttribute(name = "urceno_cerp_zuct")
    protected BigDecimal urcenoCerpZuct;
    @XmlAttribute(name = "cerp_zuct")
    protected BigDecimal cerpZuct;
    @XmlAttribute(name = "rezim", required = true)
    protected int rezim;

    /**
     * Gets the value of the dicPopl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDicPopl() {
        return dicPopl;
    }

    /**
     * Sets the value of the dicPopl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDicPopl(String value) {
        this.dicPopl = value;
    }

    /**
     * Gets the value of the dicPoverujiciho property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDicPoverujiciho() {
        return dicPoverujiciho;
    }

    /**
     * Sets the value of the dicPoverujiciho property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDicPoverujiciho(String value) {
        this.dicPoverujiciho = value;
    }

    /**
     * Gets the value of the idProvoz property.
     * 
     */
    public int getIdProvoz() {
        return idProvoz;
    }

    /**
     * Sets the value of the idProvoz property.
     * 
     */
    public void setIdProvoz(int value) {
        this.idProvoz = value;
    }

    /**
     * Gets the value of the idPokl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPokl() {
        return idPokl;
    }

    /**
     * Sets the value of the idPokl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPokl(String value) {
        this.idPokl = value;
    }

    /**
     * Gets the value of the poradCis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoradCis() {
        return poradCis;
    }

    /**
     * Sets the value of the poradCis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoradCis(String value) {
        this.poradCis = value;
    }

    /**
     * Gets the value of the datTrzby property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatTrzby() {
        return datTrzby;
    }

    /**
     * Sets the value of the datTrzby property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatTrzby(XMLGregorianCalendar value) {
        this.datTrzby = value;
    }

    /**
     * Gets the value of the celkTrzba property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCelkTrzba() {
        return celkTrzba;
    }

    /**
     * Sets the value of the celkTrzba property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCelkTrzba(BigDecimal value) {
        this.celkTrzba = value;
    }

    /**
     * Gets the value of the zaklNepodlDph property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getZaklNepodlDph() {
        return zaklNepodlDph;
    }

    /**
     * Sets the value of the zaklNepodlDph property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setZaklNepodlDph(BigDecimal value) {
        this.zaklNepodlDph = value;
    }

    /**
     * Gets the value of the zaklDan1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getZaklDan1() {
        return zaklDan1;
    }

    /**
     * Sets the value of the zaklDan1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setZaklDan1(BigDecimal value) {
        this.zaklDan1 = value;
    }

    /**
     * Gets the value of the dan1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDan1() {
        return dan1;
    }

    /**
     * Sets the value of the dan1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDan1(BigDecimal value) {
        this.dan1 = value;
    }

    /**
     * Gets the value of the zaklDan2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getZaklDan2() {
        return zaklDan2;
    }

    /**
     * Sets the value of the zaklDan2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setZaklDan2(BigDecimal value) {
        this.zaklDan2 = value;
    }

    /**
     * Gets the value of the dan2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDan2() {
        return dan2;
    }

    /**
     * Sets the value of the dan2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDan2(BigDecimal value) {
        this.dan2 = value;
    }

    /**
     * Gets the value of the zaklDan3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getZaklDan3() {
        return zaklDan3;
    }

    /**
     * Sets the value of the zaklDan3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setZaklDan3(BigDecimal value) {
        this.zaklDan3 = value;
    }

    /**
     * Gets the value of the dan3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDan3() {
        return dan3;
    }

    /**
     * Sets the value of the dan3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDan3(BigDecimal value) {
        this.dan3 = value;
    }

    /**
     * Gets the value of the cestSluz property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCestSluz() {
        return cestSluz;
    }

    /**
     * Sets the value of the cestSluz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCestSluz(BigDecimal value) {
        this.cestSluz = value;
    }

    /**
     * Gets the value of the pouzitZboz1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPouzitZboz1() {
        return pouzitZboz1;
    }

    /**
     * Sets the value of the pouzitZboz1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPouzitZboz1(BigDecimal value) {
        this.pouzitZboz1 = value;
    }

    /**
     * Gets the value of the pouzitZboz2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPouzitZboz2() {
        return pouzitZboz2;
    }

    /**
     * Sets the value of the pouzitZboz2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPouzitZboz2(BigDecimal value) {
        this.pouzitZboz2 = value;
    }

    /**
     * Gets the value of the pouzitZboz3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPouzitZboz3() {
        return pouzitZboz3;
    }

    /**
     * Sets the value of the pouzitZboz3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPouzitZboz3(BigDecimal value) {
        this.pouzitZboz3 = value;
    }

    /**
     * Gets the value of the urcenoCerpZuct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUrcenoCerpZuct() {
        return urcenoCerpZuct;
    }

    /**
     * Sets the value of the urcenoCerpZuct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUrcenoCerpZuct(BigDecimal value) {
        this.urcenoCerpZuct = value;
    }

    /**
     * Gets the value of the cerpZuct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCerpZuct() {
        return cerpZuct;
    }

    /**
     * Sets the value of the cerpZuct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCerpZuct(BigDecimal value) {
        this.cerpZuct = value;
    }

    /**
     * Gets the value of the rezim property.
     * 
     */
    public int getRezim() {
        return rezim;
    }

    /**
     * Sets the value of the rezim property.
     * 
     */
    public void setRezim(int value) {
        this.rezim = value;
    }

}
