//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 02:20:14 AM CEST 
//


package cz.mfcr.fs.eet.schema.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TrzbaHlavickaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrzbaHlavickaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="uuid_zpravy" use="required" type="{http://fs.mfcr.cz/eet/schema/v2}UUIDType" />
 *       &lt;attribute name="dat_odesl" use="required" type="{http://fs.mfcr.cz/eet/schema/v2}dateTime" />
 *       &lt;attribute name="prvni_zaslani" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="overeni" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrzbaHlavickaType")
public class TrzbaHlavickaType {

    @XmlAttribute(name = "uuid_zpravy", required = true)
    protected String uuidZpravy;
    @XmlAttribute(name = "dat_odesl", required = true)
    protected XMLGregorianCalendar datOdesl;
    @XmlAttribute(name = "prvni_zaslani", required = true)
    protected boolean prvniZaslani;
    @XmlAttribute(name = "overeni")
    protected Boolean overeni;

    /**
     * Gets the value of the uuidZpravy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuidZpravy() {
        return uuidZpravy;
    }

    /**
     * Sets the value of the uuidZpravy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuidZpravy(String value) {
        this.uuidZpravy = value;
    }

    /**
     * Gets the value of the datOdesl property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatOdesl() {
        return datOdesl;
    }

    /**
     * Sets the value of the datOdesl property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatOdesl(XMLGregorianCalendar value) {
        this.datOdesl = value;
    }

    /**
     * Gets the value of the prvniZaslani property.
     * 
     */
    public boolean isPrvniZaslani() {
        return prvniZaslani;
    }

    /**
     * Sets the value of the prvniZaslani property.
     * 
     */
    public void setPrvniZaslani(boolean value) {
        this.prvniZaslani = value;
    }

    /**
     * Gets the value of the overeni property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOvereni() {
        return overeni;
    }

    /**
     * Sets the value of the overeni property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOvereni(Boolean value) {
        this.overeni = value;
    }

}
