//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.03 at 02:20:14 AM CEST 
//


package cz.mfcr.fs.eet.schema.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrzbaKontrolniKodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrzbaKontrolniKodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pkp" type="{http://fs.mfcr.cz/eet/schema/v2}PkpElementType"/>
 *         &lt;element name="bkp" type="{http://fs.mfcr.cz/eet/schema/v2}BkpElementType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrzbaKontrolniKodyType", propOrder = {
    "pkp",
    "bkp"
})
public class TrzbaKontrolniKodyType {

    @XmlElement(required = true)
    protected PkpElementType pkp;
    @XmlElement(required = true)
    protected BkpElementType bkp;

    /**
     * Gets the value of the pkp property.
     * 
     * @return
     *     possible object is
     *     {@link PkpElementType }
     *     
     */
    public PkpElementType getPkp() {
        return pkp;
    }

    /**
     * Sets the value of the pkp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PkpElementType }
     *     
     */
    public void setPkp(PkpElementType value) {
        this.pkp = value;
    }

    /**
     * Gets the value of the bkp property.
     * 
     * @return
     *     possible object is
     *     {@link BkpElementType }
     *     
     */
    public BkpElementType getBkp() {
        return bkp;
    }

    /**
     * Sets the value of the bkp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BkpElementType }
     *     
     */
    public void setBkp(BkpElementType value) {
        this.bkp = value;
    }

}
